# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d572af2c4024bbfc2bc5eb0d6697beac458eb0edf4422588807980c57c9aed23751a7b0c175c83c40fd706bc63a1d2153be593cf5fe5e39f59e11e08d85431a3

test:
  secret_key_base: a224910629cee9e4a567f912dc28d919ea46ee2ef7a7ef72cdc1dea0a102e90447e336af6dee00dd1b0c431663c53f428eb85f9d7d8d3f9df5c0d70009eecff2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
